### ISSUE TITLE
New JetID recommendations

### ISSUE THREAD

**Issue by peiffer** [UHH2/UHH2#153]
The new recommendations for the jet ID (https://twiki.cern.ch/twiki/bin/view/CMS/JetID#Recommendations_for_13_TeV_data) have to be implemented.

**Comment by dgonzal** [comment]
I had a look today, is the pfID flag from core/include/Jet.h used during the creation of the ntuples ?

**Comment by peiffer** [comment]
The pfID from Jet.h isn't used anywhere in the code. The jet ID should better go into common/src/JetIds.cxx.

**Comment by dgonzal** [comment]
If it is not used it should be kicked out ? Otherwise we will have duplicated code

**Comment by peiffer** [comment]
Yes, for consistency of all IDs, I would drop the ID from Jet.h and implement all jet IDs in JetIds.cxx.

**Comment by dgonzal** [comment]
#159 
compiles and runs
