### ISSUE TITLE
[RunII_106X_v2] BTagCalibration tool depreciated

### ISSUE THREAD

**Issue by MatthiesC** [UHH2/UHH2#1612]
According to https://hypernews.cern.ch/HyperNews/CMS/get/btag/1918.html the old BTagCalibration tool that we currently still use in UHH2 is depreciated and not any longer compatible with the newest format of the CSV files holding the b-tagging scale factors.

Either we switch to the central JSON format (but I am not sure right now if this is only usable with NanoAOD - we use MiniAOD) or we adjust the BTagCalibration tool and related code-bits:

https://github.com/UHH2/UHH2/blob/RunII_106X_v2/common/include/BTagCalibrationStandalone.h
https://github.com/UHH2/UHH2/blob/RunII_106X_v2/common/src/BTagCalibrationStandalone.cc
https://github.com/UHH2/UHH2/blob/RunII_106X_v2/common/src/MCWeight.cxx (all b-tag related classes therein)

**Comment by finnlabe** [comment]
Only for documentation sake, as I just saw this issue: the necessary changes to handle the new csv file structure were implemented here: https://github.com/UHH2/UHH2/pull/1620

However, there seems to be another issue with commas inside the formulas in the csv file, as discussed here: https://github.com/UHH2/UHH2/pull/1633

**Comment by MatthiesC** [comment]
With #1637 this issue is resolved. We now use a custom CSV reader.
