### ISSUE TITLE
do we apply the L2L3Residual JEC for data?

### ISSUE THREAD

**Issue by missirol** [UHH2/UHH2#249]
from here https://github.com/UHH2/UHH2/blob/master/core/python/ntuplewriter.py#L338 it seems we are not. (is that done inside 'AddJetCollection' by any chance?)

PS this may be marginal because we re-apply the JECs offline, but still..

**Comment by peiffer** [comment]
Hi Marino,

indeed, seems that the L2L3Residual corrections are not applied for data. I checked the pyhton dump file and all additional jets collections have just 
    
levels = cms.vstring('L1FastJet', 
        'L2Relative', 
        'L3Absolute'),

**Comment by imarches** [comment]
Dear all,

yes, this should be probably added. I see them, however, in the recorrector, which we typically apply, so probably this has so far compensated for this.

**Comment by peiffer** [comment]
I have added the L2L3Residual corrections for data, see #250
