### ISSUE TITLE
mc pileup info in miniAOD-v2

### ISSUE THREAD

**Issue by missirol** [UHH2/UHH2#251]
for miniAOD-v2 samples, "addPileupInfo" needs to be replaced by "slimmedAddPileupInfo", (i think only) here

https://github.com/UHH2/UHH2/blob/master/core/plugins/NtupleWriter.cc#L577

if one runs the current master branch on a miniAOD-v2 sample, the MC pileup info (needed for pu reweighting) are not getting filled.
there is no error coming up, what happens is just that the block in here
https://github.com/UHH2/UHH2/blob/master/core/plugins/NtupleWriter.cc#L581
is never accessed

**Comment by peiffer** [comment]
Hi Marino,

thanks for spotting this. I have fixed the input collection for the pile-up info, see #252.
