### ISSUE TITLE
CMS TopTag

### ISSUE THREAD

**Issue by dgonzal** [UHH2/UHH2#301]
Hi,
I tried using the CMSTopTag with the v2 samples with the slimmedJetsAK8_SoftDrop & patJetsAk8CHSJetsSoftDropPacked_daughters, since I didn't see a collection with CMSTopTag anymore. 
Is the toptagging information now stored differently or not at all ? Do I miss something ?

Cheers & thanks 

Daniel

**Comment by imarches** [comment]
The cms top tagger is not supported anymore by JME, please, switch to the softdrop-based tagger
