### ISSUE TITLE
Mother links for genParticles are not working correctly.

### ISSUE THREAD

**Issue by HeinAtCERN** [UHH2/UHH2#36]
I just noticed that I could find the mother of a tprime by asking every particle for every daughter pdgId, but the tprime does not have the link to it's mother set.

EDIT: working with these files:
/nfs/dust/cms/user/ottjoc/gc-output/PHYS14v2/signals_WZ/MC_TpJ_TH_M800_20x25_11_Ntuple.root
/nfs/dust/cms/user/ottjoc/gc-output/PHYS14v2/signals_WZ/MC_TpJ_TH_M800_20x25_12_Ntuple.root
/nfs/dust/cms/user/ottjoc/gc-output/PHYS14v2/signals_WZ/MC_TpJ_TH_M800_20x25_13_Ntuple.root

EDIT2:
Some of the higgs and w particles have no daughters at all.

**Comment by jottCern** [comment]
According to the tests, situation seems to be improved for new ntuples. Missing H daughters still appear, but at the sub-percent-level.

**Comment by HeinAtCERN** [comment]
Strange. But ok, I'll keep it in mind. For now it's good.
