### ISSUE TITLE
new CSVv2.csv for 76X doesn't work on the 76X branch

### ISSUE THREAD

**Issue by emanueleusai** [UHH2/UHH2#403]
ERROR in BTagCalibration: (OperatingPoint, measurementType, sysType) not available: 1, comb, upterminate called after throwing an instance of 'std::runtime_error'
  what():  Registry: exception while trying to build type 'SelectionModule': std::exception
Aborted

The old one works fine. It seems like some particular combinations of OP/measurement/systematic aren't available in the new database

**Comment by imarches** [comment]
https://twiki.cern.ch/twiki/bin/viewauth/CMS/BtagRecommendation76X

yes, the payloads have new name

"incl" for light jets
"mujets" for b and c jets

**Comment by emanueleusai** [comment]
must have missed that :(
worked like a charm
closing..

**Comment by dgonzal** [comment]
#406 changes default value from "comb" to "incl"
