### ISSUE TITLE
CMSSW_7_4_0

### ISSUE THREAD

**Issue by dgonzal** [UHH2/UHH2#86]
I just tested CMSSW_7_4_0 with suhh2. During runtime an error is thrown which has to do with the dictionaries. Traced the error back and it comes from the change from root 5 to 6 from cint to cling. 
Cling creates additional pcm files which have to be present in the same dir as the .so files at runtime.  
The shortterm fix for the moment is to copy them by hand.

**Comment by emanueleusai** [comment]
Hi Daniel, I have installed and compiled UHH2 on 7_4_3 without errors, did you recompile SFrame?

**Comment by dgonzal** [comment]
Nice that it worked, recompiled everything back then
